---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[nsdx_test::default]
      - recipe[nsdx::master]
    attributes:
      nsdx:
        master:
          fqdn: ns1.example.com
  - name: databag
    run_list:
      - recipe[nsdx::databag]
      - recipe[nsdx::master]
    data_bags_path: "test/integration/data_bags"
    attributes:
      nsdx:
        master:
          fqdn: ns1.example.com
